version: 2.1

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

jobs:
  build:
    working_directory: ~/SimpleApplication
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache: 
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths: 
            - ./node_modules
            - ./package-lock.json

  deploy:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Deploy to AWS EC2
          command: |
            scp -i "/Users/GGmachines_Gaming/OneDrive/Desktop/devops/DevOpsSecKey" -r ./ ubuntu@ec2-13-49-231-207.eu-north-1.compute.amazonaws.com:/home/ubuntu/myApp
